name: ci
permissions:
  contents: read

on: push

jobs:
  auto-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: use Node.js
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: install dependency
        run: pnpm i
      - name: test format
        run: pnpm prettier
      - name: test linter
        run: pnpm lint
      - name: test compiler
        run: pnpm tsc
      - name: auto code review via knip
        run: pnpm knip
      - name: test unit-testing and integration-testing
        run: pnpm test
