name: Cron job for release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1'

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
      - name: Check whether pr already exists
        id: check_pr
        env:
          HEAD_MESSAGE: ${{ github.event.head_commit.message }}
        run: |
          COMMIT_MESSAGE=$(echo "${HEAD_MESSAGE}" | sed -n -e 1p)
          echo "message=${COMMIT_MESSAGE}" >> "$GITHUB_OUTPUT"
          echo "count=$(gh pr list -S 'Deploying resource to production'in:title | wc -l)" >> "$GITHUB_OUTPUT"
      - name: Create Release Pull Request
        if: ${{ steps.check_pr.outputs.count == 0 }}
        run: |
          gh pr create \
            -B master \
            -t 'Deploying resource to production ${{ steps.check_pr.outputs.message }}' \
