name: Basic Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'
      - name: install dependency
        run: yarn install
      - name: test format
        run: yarn run prettier
      - name: test linter
        run: yarn run lint
      - name: test style lint
        run: yarn run lint-style
      - name: test compiler
        run: yarn run compiler-check
      - name: auto code review via knip
        run: yarn run knip
      - name: test unit-testing and integration-testing
        run: yarn run jest --ci
