name: auto-test

on: push

jobs:
  auto-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - name: use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: install pnpm
        run: npm install -g pnpm
      - name: install dependency
        run: pnpm install
      - name: test format
        run: pnpm run prettier
      - name: test linter
        run: pnpm run lint
      - name: test style lint
        run: pnpm run lint-style
      - name: test compiler
        run: pnpm run compiler-check
      - name: auto code review via knip
        run: pnpm run knip
      - name: test unit-testing and integration-testing
        run: pnpm run jest --ci
