name: auto-test
permissions:
  contents: read

on: push

jobs:
  auto-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6
      - name: use Node.js
        uses: pnpm/action-setup@v6
      - name: install dependency
        run: pnpm i
      - name: test format
        run: pnpm prettier
      - name: test linter
        run: pnpm lint
      - name: test compiler
        run: pnpm tsc
      - name: auto code review via knip
        run: pnpm knip
      - name: test unit-testing and integration-testing
        run: pnpm test
