name: UI Regression Test

 on: push

 jobs:
   test:
     runs-on: ubuntu-latest

     steps:
       - run: node -v
       - run: yarn -v
       - uses: actions/checkout@v2
       - run: yarn install
       - run: yarn run reg-check