name: Unit Test And Linter Check

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: node -v
      - run: yarn -v
      - uses: actions/checkout@v3
      - run: yarn install
      - run: yarn run prettier
      - run: yarn run lint
      - run: yarn run compiler-check
      - run: yarn run lint-style
      - run: yarn run jest
